"""historique_retention_dashboard

Revision ID: 6d3609df78a5
Revises: e97e628c9c39
Create Date: 2026-05-12 05:03:05.387767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3609df78a5'
down_revision: Union[str, Sequence[str], None] = 'e97e628c9c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travaux', sa.Column('chemin_animation', sa.String(), nullable=True))
    op.add_column('travaux', sa.Column('taille_original', sa.Integer(), nullable=True))
    op.add_column('travaux', sa.Column('taille_resultat', sa.Integer(), nullable=True))
    op.add_column('utilisateurs', sa.Column('retention_jours', sa.Integer(), nullable=False, server_default='30'))
    op.create_check_constraint('ck_utilisateurs_retention', 'utilisateurs', 'retention_jours IN (7, 30, 90)')
    op.add_column('utilisateurs', sa.Column('derniere_activite', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_utilisateurs_retention', 'utilisateurs')
    op.drop_column('utilisateurs', 'derniere_activite')
    op.drop_column('utilisateurs', 'retention_jours')
    op.drop_column('travaux', 'taille_resultat')
    op.drop_column('travaux', 'taille_original')
    op.drop_column('travaux', 'chemin_animation')
    # ### end Alembic commands ###
