"""add_credits_perpetuels

Revision ID: 8dc346ab91ac
Revises: 31fffebd0c35
Create Date: 2026-05-19 16:38:35.312047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dc346ab91ac'
down_revision: Union[str, Sequence[str], None] = 'd9e4a25a8bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop sibling subagent's duplicate table
    op.drop_index(op.f('ix_imported_photos_supprime_le'), table_name='imported_photos')
    op.drop_index(op.f('ix_imported_photos_utilisateur_id'), table_name='imported_photos')
    op.drop_table('imported_photos')
    # Add credits_perpetuels with server default to avoid NOT NULL on existing rows
    op.add_column('utilisateurs', sa.Column('credits_perpetuels', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'credits_perpetuels')
    op.create_table('imported_photos',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chemin_original', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('b2_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('taille', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nom_fichier', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('cree_le', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('supprime_le', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], name=op.f('imported_photos_utilisateur_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('imported_photos_pkey'))
    )
    op.create_index(op.f('ix_imported_photos_utilisateur_id'), 'imported_photos', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_imported_photos_supprime_le'), 'imported_photos', ['supprime_le'], unique=False)
    # ### end Alembic commands ###
