"""add_consentements_table

Revision ID: bf5fe61add2f
Revises: 6d3609df78a5
Create Date: 2026-05-19 10:49:16.561736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf5fe61add2f'
down_revision: Union[str, Sequence[str], None] = '6d3609df78a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consentements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('type_consentement', sa.String(), nullable=False),
    sa.Column('accepte', sa.Boolean(), nullable=False),
    sa.Column('version_texte', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('contexte', sa.Text(), nullable=True),
    sa.Column('accorde_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retire_le', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type_consentement IN ('cgv_checkout', 'renonciation_retractation', 'rgpd_biometrique', 'rgpd_ia')", name='ck_consentements_type'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consentements_user_type', 'consentements', ['utilisateur_id', 'type_consentement'], unique=False)
    op.create_index(op.f('ix_consentements_accorde_le'), 'consentements', ['accorde_le'], unique=False)
    op.create_index(op.f('ix_consentements_email'), 'consentements', ['email'], unique=False)
    op.create_index(op.f('ix_consentements_type_consentement'), 'consentements', ['type_consentement'], unique=False)
    op.create_index(op.f('ix_consentements_utilisateur_id'), 'consentements', ['utilisateur_id'], unique=False)
    op.drop_constraint(op.f('stripe_events_event_id_key'), 'stripe_events', type_='unique')
    op.create_index(op.f('ix_stripe_events_event_id'), 'stripe_events', ['event_id'], unique=True)
    op.create_index('idx_travaux_user_date', 'travaux', ['utilisateur_id', sa.literal_column('cree_le DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_travaux_user_date', table_name='travaux')
    op.drop_index(op.f('ix_stripe_events_event_id'), table_name='stripe_events')
    op.create_unique_constraint(op.f('stripe_events_event_id_key'), 'stripe_events', ['event_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_consentements_utilisateur_id'), table_name='consentements')
    op.drop_index(op.f('ix_consentements_type_consentement'), table_name='consentements')
    op.drop_index(op.f('ix_consentements_email'), table_name='consentements')
    op.drop_index(op.f('ix_consentements_accorde_le'), table_name='consentements')
    op.drop_index('idx_consentements_user_type', table_name='consentements')
    op.drop_table('consentements')
    # ### end Alembic commands ###
