"""add_images_importees

Revision ID: d9e4a25a8bc3
Revises: bf5fe61add2f
Create Date: 2026-05-19 16:25:36.161611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e4a25a8bc3'
down_revision: Union[str, Sequence[str], None] = 'bf5fe61add2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images_importees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('chemin_fichier', sa.String(), nullable=False),
    sa.Column('nom_origine', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('taille_octets', sa.Integer(), nullable=False),
    sa.Column('largeur', sa.Integer(), nullable=True),
    sa.Column('hauteur', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_utilisation', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mime_type IN ('image/jpeg', 'image/png', 'image/webp')", name='ck_lib_mime'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lib_user_date', 'images_importees', ['utilisateur_id', sa.literal_column('cree_le DESC')], unique=False)
    op.create_index(op.f('ix_images_importees_cree_le'), 'images_importees', ['cree_le'], unique=False)
    op.create_index(op.f('ix_images_importees_utilisateur_id'), 'images_importees', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_importees_utilisateur_id'), table_name='images_importees')
    op.drop_index(op.f('ix_images_importees_cree_le'), table_name='images_importees')
    op.drop_index('idx_lib_user_date', table_name='images_importees')
    op.drop_table('images_importees')
    # ### end Alembic commands ###
