"""initial_schema

Revision ID: e97e628c9c39
Revises: 
Create Date: 2026-05-11 13:30:57.376113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97e628c9c39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('email_utilisateur', sa.String(), nullable=True),
    sa.Column('derniere_attribution_credits', sa.String(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("statut IN ('cree', 'actif', 'impaye', 'resilie', 'expire')", name='ck_abonnements_statut'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_abonnements_statut', 'abonnements', ['statut'], unique=False)
    op.create_index('idx_abonnements_stripe_customer', 'abonnements', ['stripe_customer_id'], unique=False)
    op.create_index('idx_abonnements_stripe_subscription', 'abonnements', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_abonnements_stripe_customer_id'), 'abonnements', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_abonnements_stripe_subscription_id'), 'abonnements', ['stripe_subscription_id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('essais_restants', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('est_abonne', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('oauth_provider', sa.String(), nullable=True),
    sa.Column('oauth_provider_id', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('animations_utilisees', sa.Integer(), nullable=True),
    sa.Column('mois_animation_courant', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_provider', 'utilisateurs', ['oauth_provider', 'oauth_provider_id'], unique=False)
    op.create_index('idx_utilisateurs_email', 'utilisateurs', ['email'], unique=False)
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_table('achats_credits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('nombre_credits', sa.Integer(), nullable=False),
    sa.Column('montant_euros', sa.Float(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achats_credits_utilisateur_id'), 'achats_credits', ['utilisateur_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evenement', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('reussite', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_date', 'audit_logs', ['cree_le'], unique=False)
    op.create_index('idx_audit_email', 'audit_logs', ['email'], unique=False)
    op.create_index('idx_audit_evenement', 'audit_logs', ['evenement'], unique=False)
    op.create_index('idx_audit_reussite', 'audit_logs', ['reussite'], unique=False)
    op.create_index(op.f('ix_audit_logs_cree_le'), 'audit_logs', ['cree_le'], unique=False)
    op.create_index(op.f('ix_audit_logs_email'), 'audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_audit_logs_evenement'), 'audit_logs', ['evenement'], unique=False)
    op.create_table('essais_gratuits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('type_travail', sa.String(), nullable=False),
    sa.Column('travail_id', sa.String(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type_travail IN ('analyse', 'restauration', 'animation')", name='ck_essais_type'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_essais_gratuits_utilisateur_id'), 'essais_gratuits', ['utilisateur_id'], unique=False)
    op.create_table('reinitialisation_mdp',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilise', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reinitialisation_mdp_token'), 'reinitialisation_mdp', ['token'], unique=True)
    op.create_index(op.f('ix_reinitialisation_mdp_utilisateur_id'), 'reinitialisation_mdp', ['utilisateur_id'], unique=False)
    op.create_table('travaux',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=True),
    sa.Column('chemin_photo', sa.String(), nullable=True),
    sa.Column('chemin_resultat', sa.String(), nullable=True),
    sa.Column('resultat_json', sa.Text(), nullable=True),
    sa.Column('job_externe_id', sa.String(), nullable=True),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("statut IN ('cree', 'en_cours', 'termine', 'erreur')", name='ck_travaux_statut'),
    sa.CheckConstraint("type IN ('analyse', 'restauration', 'animation')", name='ck_travaux_type'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_travaux_statut', 'travaux', ['statut'], unique=False)
    op.create_index('idx_travaux_type', 'travaux', ['type'], unique=False)
    op.create_index('idx_travaux_utilisateur', 'travaux', ['utilisateur_id'], unique=False)
    op.create_index(op.f('ix_travaux_utilisateur_id'), 'travaux', ['utilisateur_id'], unique=False)
    op.create_table('consommation_credits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('travail_id', sa.String(), nullable=False),
    sa.Column('type_operation', sa.String(), nullable=False),
    sa.Column('credits_utilises', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type_operation IN ('restauration', 'animation')", name='ck_consommation_type'),
    sa.ForeignKeyConstraint(['travail_id'], ['travaux.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consommation_credits_utilisateur_id'), 'consommation_credits', ['utilisateur_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consommation_credits_utilisateur_id'), table_name='consommation_credits')
    op.drop_table('consommation_credits')
    op.drop_index(op.f('ix_travaux_utilisateur_id'), table_name='travaux')
    op.drop_index('idx_travaux_utilisateur', table_name='travaux')
    op.drop_index('idx_travaux_type', table_name='travaux')
    op.drop_index('idx_travaux_statut', table_name='travaux')
    op.drop_table('travaux')
    op.drop_index(op.f('ix_reinitialisation_mdp_utilisateur_id'), table_name='reinitialisation_mdp')
    op.drop_index(op.f('ix_reinitialisation_mdp_token'), table_name='reinitialisation_mdp')
    op.drop_table('reinitialisation_mdp')
    op.drop_index(op.f('ix_essais_gratuits_utilisateur_id'), table_name='essais_gratuits')
    op.drop_table('essais_gratuits')
    op.drop_index(op.f('ix_audit_logs_evenement'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_email'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_cree_le'), table_name='audit_logs')
    op.drop_index('idx_audit_reussite', table_name='audit_logs')
    op.drop_index('idx_audit_evenement', table_name='audit_logs')
    op.drop_index('idx_audit_email', table_name='audit_logs')
    op.drop_index('idx_audit_date', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_achats_credits_utilisateur_id'), table_name='achats_credits')
    op.drop_table('achats_credits')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_index('idx_utilisateurs_email', table_name='utilisateurs')
    op.drop_index('idx_oauth_provider', table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_abonnements_stripe_subscription_id'), table_name='abonnements')
    op.drop_index(op.f('ix_abonnements_stripe_customer_id'), table_name='abonnements')
    op.drop_index('idx_abonnements_stripe_subscription', table_name='abonnements')
    op.drop_index('idx_abonnements_stripe_customer', table_name='abonnements')
    op.drop_index('idx_abonnements_statut', table_name='abonnements')
    op.drop_table('abonnements')
    # ### end Alembic commands ###
