services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    network_mode: host
    command:
      - "--api.insecure=false"
      - "--providers.docker=false"
      - "--providers.file.filename=/etc/traefik/flashback-dynamic.yml"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "./traefik:/letsencrypt"
      - "../../traefik/flashback-dynamic.yml:/etc/traefik/flashback-dynamic.yml:ro"
    restart: unless-stopped
